version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
